### ISSUE TITLE
Possible to ad Ratiocolor plugin support?

### ISSUE THREAD

**Issue by DasBlatz** [exetico/FlatUI#2]
Possible to ad Ratiocolor plugin support?

[RatioColor](https://github.com/Gyran/rutorrent-ratiocolor)

Thanks

**Comment by exetico** [comment]
Hi'

Somehow i skipped this request. I will give it a try in near feature :-)

**Comment by exetico** [comment]
Hi @DasBlatz 

Cause of using of "!important;" in custom styles, the radio-colors isn't working like it should.

I have made a pull request to the RatioColor git:
https://github.com/Gyran/rutorrent-ratiocolor/pull/1

If you like, you can just replace init.js witht the this file:
https://raw.githubusercontent.com/exetico/rutorrent-ratiocolor/2863a0d10682ca3d87487569e57d01e674c46132/init.js

Best Regards,

**Comment by exetico** [comment]
@DasBlatz - I will just let you know that Gyran has accepted my pull-request. If you get any issues in the future, then please let me know.

Gyran fixed push-right, so i am able to make the fixes right away :-)
