### ISSUE TITLE
Missing autodll-irc1.png and autodll-irc2.png images

### ISSUE THREAD

**Issue by whookid** [exetico/FlatUI#3]
Hi,

Nice work on the themes!
Just wanted to let you know that autodll-irc1.png and autodll-irc2.png are missing from the images folder.

Any change that you might add them?

Thanks!
~whookid

**Comment by exetico** [comment]
Hi'

Sorry for the late reply. Is the .png-files normally provided, or is it following with a addon? I'm trying to figure out how i will fix it. Normally i'm replacing the icons with FontAwesome's :-)

Best Regards

**Comment by whookid** [comment]
Hi,

It is provided via an addon, you can find the repository here: https://github.com/autodl-community/autodl-rutorrent .

Regards
~ whookid

PS:  fa-retweet or fa-magic would be sweet ;)

**Comment by exetico** [comment]
![image](https://cloud.githubusercontent.com/assets/3549445/22181976/4b7b9f14-e099-11e6-9cdb-fddeced9b22e.png)
Sorry for the delay :-)

**Comment by whookid** [comment]
Looks good, thanks! ;-)
