### ISSUE TITLE
Remove torrent popup cuts off

### ISSUE THREAD

**Issue by whookid** [exetico/FlatUI#4]
The buttons are not visible: http://imgur.com/sL9qtEC

**Comment by exetico** [comment]
![image](https://cloud.githubusercontent.com/assets/3549445/22181748/b63372f2-e092-11e6-8760-79a402613214.png)
Hi'

Are you using the normal way to delete content?
"Remove" or "Remove and..." > "Delete Data"

I did try with a single line and multiple, both without issues. Please note that ruTorrent will troubling with deleting the content, if the CPU, Disk and RAM is under heavily usage.

I'm currently running with the following version:
0.9.6/0.13.6

Is the issue still going on? Also, please let me know the device and browser type and version.

**Comment by exetico** [comment]
Oh..
![image](https://cloud.githubusercontent.com/assets/3549445/22181787/985cf86a-e093-11e6-8d8a-eaa69bf5c91a.png)
It looks like the normal ruTorrent theme have some troubles.

After adding height:auto everything is working like is should. Are we talking about the same issue? :-)
![image](https://cloud.githubusercontent.com/assets/3549445/22181790/bbd2c2fc-e093-11e6-851d-61df8cf757f2.png)

(Note to self: Add "height:auto" or another fix, to secure that all content is showed in popups. .dlg-window#yesnoDlg)

**Comment by exetico** [comment]
![image](https://cloud.githubusercontent.com/assets/3549445/22181895/ba448f62-e096-11e6-92f8-a4466174c7fe.png)
Fixed. Please let me know, if this fix makes any other issues with other popups, with the .dlg-window class.

**Comment by whookid** [comment]
I can confirm it has been fixed, thanks! I will let you know if I come across any other issues.
