### ISSUE TITLE
Make it mobile?

### ISSUE THREAD

**Issue by PontusTideman** [exetico/FlatUI#5]
Hi mate!

Using your theme with the latest version of rTorrent and ruTorrent, but when using my Nexus 6P I see that the theme is not mobile.

Are you working to fix this or?

**Comment by exetico** [comment]
Hi

At the moment, it's not a thing i will look into. Please take a look at the
readme - here you can find my preffered mobile plugin.


Den 18. maj 2017 07.23 skrev "Pontus Öhman" <notifications@github.com>:

Hi mate!

Using your theme with the latest version of rTorrent and ruTorrent, but
when using my Nexus 6P I see that the theme is not mobile.

Are you working to fix this or?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/exetico/FlatUI/issues/5>, or mute the thread

**Comment by phonicmouse** [comment]
I think it would be very useful. +1 for this.

**Comment by exetico** [comment]
Hi @PontusTideman  and @phonicmouse 

I've found a big of time in the last couple of mounts, and thought a bit about the mobile part, while trying to seperate each styling-component. The theme is a real mess to be honest - but it's starting to work out.

[FlatUI_Dark.zip](https://github.com/exetico/FlatUI/files/5505388/FlatUI_Dark.zip)
Here's the latest dev version of the new version. Let me know, if you found any issues.

For the module part, I'm not sure that I else can do to make it better. I've though about forcing all popup/windows to full width and height, and maybe extend each line a bit - and implementing a bit mor air about other elements too, if the screen-resolution is more or less like a phone.

Let me know what you guys think. I'll push the changes in a few weeks or so, if I get the proper amount of feedback.

**Comment by exetico** [comment]
And here's the source-code, for the latest changes:
https://github.com/exetico/FlatUI/tree/covid19-remake/FlatUI_Dark

**Comment by PontusTideman** [comment]
Woho! :D Cheers mate. 👍 

Will take a look at this in the near feature. Since it's 3 years ago I wrote this.

**Comment by exetico** [comment]
No problem!

Please note that it's primary optimized a bit, but I'm open for other
suggestions to more changes down the line.

I had trashed the project myself (but I'm still using the theme)...

A few weeks back I had a few hours to spend on someting else, than new
things.

After seperating most of the styling-elements, it's now just a bit easier
to handle new changes in the future :-)

_But I'm not saying the code it well made, that's for sure. Many are still
handled in old fashion way. But, IT'S WORKING._ 😀

fre. 13. nov. 2020 13.31 skrev Pontus Tideman <notifications@github.com>:

**Comment by exetico** [comment]
The covid10 remake are now published. A better mobile version won't be created - but fell free to report bugs, and even create PR's if you have idea's to specific mobile-optimizations.

https://github.com/exetico/FlatUI/releases/tag/2.0
