### ISSUE TITLE
[FlatUI Dark] Icons not showing properly

### ISSUE THREAD

**Issue by Ptikrazy** [exetico/FlatUI#7]
Hello !

Great themes, been using the Dark one for quite a while now.
I had to reinstall my setup today, and for some reason the icons are not showing properly.
Do you have any idea why ?

Thanks a lot !

Here's the link to the theme: https://github.com/exetico/FlatUI/tree/master/FlatUI_Dark

![image](https://user-images.githubusercontent.com/11388339/141878396-cca40ed1-4939-4ed0-ac66-3747e6012e45.png)

**Comment by exetico** [comment]
Hi

Thanks!

Please provide your version of ruTorrent and Chrome. 

Did you download all the files, related to the theme? (not only the CSS-file) 

Are you running the latest version of ruTorrent? If not, please test with that.

Maybe font-awesome aren't fetched properly.  Open the 'Debug panel' in your browser, and go to the network tab. Hereafter, reload the page. Validate that the source-files are dowbloaded correctly.

Also, please try in the latest version of Chrome, just to check, if it's a browser specific problem.

**Comment by Ptikrazy** [comment]
Hello,

Just tried today and everything is back to normal without me changing anything ! I suspect a cache issue, I was certain I emptied it yesterday but hey, maybe not.

You can close the issue :) FYI I'm on rutorrent 3.10 and Firefox 94.0.1 (latest to date)
